// -----------------------------------------------------------------------
// <autogenerated>
//    This code was generated from a template.
// 
//    Changes to this file may cause incorrect behaviour and will be lost
//    if the code is regenerated.
// </autogenerated>
// ------------------------------------------------------------------------
namespace ReactiveSearch.UnitTests.Services.Api.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class DuckDuckGoApiMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.Api.IDuckDuckGoApi>, global::ReactiveSearch.Services.Api.IDuckDuckGoApi
    {
        public DuckDuckGoApiMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::System.IObservable<global::ReactiveSearch.Services.Api.DuckDuckGoSearchResult> Search(System.String query)
        {
            return this.Apply(x => x.Search(query));
        }
    }
}
namespace ReactiveSearch.UnitTests.Services.Api.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class DuckDuckGoApiServiceMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.Api.IDuckDuckGoApiService>, global::ReactiveSearch.Services.Api.IDuckDuckGoApiService
    {
        public DuckDuckGoApiServiceMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::ReactiveSearch.Services.Api.IDuckDuckGoApi Background
        {
            get
            {
                return this.Apply(x => x.Background);
            }
        }

        public global::ReactiveSearch.Services.Api.IDuckDuckGoApi Speculative
        {
            get
            {
                return this.Apply(x => x.Speculative);
            }
        }

        public global::ReactiveSearch.Services.Api.IDuckDuckGoApi UserInitiated
        {
            get
            {
                return this.Apply(x => x.UserInitiated);
            }
        }
    }
}
namespace ReactiveSearch.UnitTests.Services.Delay.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class DelayServiceMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.Delay.IDelayService>, global::ReactiveSearch.Services.Delay.IDelayService
    {
        public DelayServiceMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::System.IObservable<global::System.Reactive.Unit> Delay(global::System.TimeSpan duration)
        {
            return this.Apply(x => x.Delay(duration));
        }
    }
}
namespace ReactiveSearch.UnitTests.Services.NetworkConnectivity.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class NetworkConnectivityServiceMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.NetworkConnectivity.INetworkConnectivityService>, global::ReactiveSearch.Services.NetworkConnectivity.INetworkConnectivityService
    {
        public NetworkConnectivityServiceMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::System.IObservable<System.Boolean> IsInternetConnectivityAvailable()
        {
            return this.Apply(x => x.IsInternetConnectivityAvailable());
        }

        public global::System.IObservable<System.Boolean> IsReachable(System.String host, System.Int32 port, System.Int32 msTimeout)
        {
            return this.Apply(x => x.IsReachable(host, port, msTimeout));
        }

        public global::System.IObservable<global::System.Collections.Generic.IEnumerable<global::Plugin.Connectivity.Abstractions.ConnectionType>> InternetConnectivity()
        {
            return this.Apply(x => x.InternetConnectivity());
        }
    }
}
namespace ReactiveSearch.UnitTests.Services.Search.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class SearchServiceMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.Search.ISearchService>, global::ReactiveSearch.Services.Search.ISearchService
    {
        public SearchServiceMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::System.IObservable<global::ReactiveSearch.Services.Api.DuckDuckGoSearchResult> Search(System.String query)
        {
            return this.Apply(x => x.Search(query));
        }
    }
}
namespace ReactiveSearch.UnitTests.Services.State.Mocks
{
    [System.CodeDom.Compiler.GeneratedCode("PCLMock", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGenerated]
    public partial class StateServiceMock : global::PCLMock.MockBase<global::ReactiveSearch.Services.State.IStateService>, global::ReactiveSearch.Services.State.IStateService
    {
        public StateServiceMock(global::PCLMock.MockBehavior behavior = global::PCLMock.MockBehavior.Strict): base (behavior)
        {
            if ((behavior) == (global::PCLMock.MockBehavior.Loose))
            {
                ConfigureLooseBehavior();
            }
        }

        partial void ConfigureLooseBehavior();
        public global::System.IObservable<T> Get<T>(System.String key)
        {
            return this.Apply(x => x.Get<T>(key));
        }

        public global::System.IObservable<T> GetAndFetchLatest<T>(System.String key, global::System.Func<global::System.Threading.Tasks.Task<T>> fetchFunc, global::System.Func<global::System.DateTimeOffset, System.Boolean> fetchPredicate, global::System.DateTimeOffset? absoluteExpiration)
        {
            return this.Apply(x => x.GetAndFetchLatest<T>(key, fetchFunc, fetchPredicate, absoluteExpiration));
        }

        public global::System.IObservable<T> GetOrFetch<T>(System.String key, global::System.Func<global::System.Threading.Tasks.Task<T>> fetchFunc, global::System.DateTimeOffset? absoluteExpiration)
        {
            return this.Apply(x => x.GetOrFetch<T>(key, fetchFunc, absoluteExpiration));
        }

        public global::System.IObservable<global::System.Reactive.Unit> Invalidate(System.String key)
        {
            return this.Apply(x => x.Invalidate(key));
        }

        public global::System.IDisposable RegisterSaveCallback(global::ReactiveSearch.Services.State.SaveCallback saveCallback)
        {
            return this.Apply(x => x.RegisterSaveCallback(saveCallback));
        }

        public global::System.IObservable<global::System.Reactive.Unit> Remove<T>(System.String key)
        {
            return this.Apply(x => x.Remove<T>(key));
        }

        public global::System.IObservable<global::System.Reactive.Unit> Save()
        {
            return this.Apply(x => x.Save());
        }

        public global::System.IObservable<global::System.Reactive.Unit> Set<T>(System.String key, T value)
        {
            return this.Apply(x => x.Set<T>(key, value));
        }

        public global::System.IObservable<global::System.Reactive.Unit> Set<T>(System.String key, T value, global::System.TimeSpan expiration)
        {
            return this.Apply(x => x.Set<T>(key, value, expiration));
        }
    }
}

